# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.16.3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
            
      - run: npm run tslint
      - run: npm run build
      
      - add_ssh_keys:
          fingerprints:
            - "7b:42:e7:9f:87:83:6f:ad:58:ba:4d:cc:82:4a:75:5c"
      
      - run: sudo apt install rsync -y
      - run: ssh -o StrictHostKeyChecking=no hyunsub@home.hyunsub.kim "rm -rf ~/docker/frontend/*"
      - run: rsync -ah --progress -e "ssh -o StrictHostKeyChecking=no" ~/repo/build/ hyunsub@home.hyunsub.kim:/home/hyunsub/docker/frontend/
      - run: rsync -ah --progress -e "ssh -o StrictHostKeyChecking=no" ~/repo/default.conf hyunsub@home.hyunsub.kim:/home/hyunsub/docker/frontend/
